pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code...'
                git branch: "main", url: 'https://github.com/h1ddengames/Project-Template.git'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh "mvn -B clean test -Duser.home=$HOME/.m2 --file pom.xml"
            }
        }

        stage('Build') {
            steps {
                echo 'Building project artifacts...'
                sh "mvn -B package -Dmaven.test.skip=true -Duser.home=$HOME/.m2 --file pom.xml"
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying project artifacts...'
//                 export TIME=$(TZ='America/Los_Angeles' date +"%m-%d-%Y--%r" | tr -d "[:space:]" | sed 's/:/./g')
//                 echo $TIME
//                 mkdir -p output/${TIME}/jars output/${TIME}/javadocs output/${TIME}/reports output/${TIME}/results
//                 cp target/$(grep -o "<artifactId>.*</artifactId>" pom.xml | head -1 | sed "s#<artifactId>###\g" | sed "s#</artifactId>###\g")-$(grep -o "<version>.*</version>" pom.xml | head -1 | sed "s#<version>###\g" | sed "s#</version>###\g").jar output/$TIME/jars
//
//                 cp -R target/javadocs/apidocs/* output/${TIME}/javadocs
//                 cp -R artifacts/allure-reports/* output/${TIME}/reports
//                 cp -R artifacts/allure-results/* output/${TIME}/results
            }
        }
    }
}