# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    #- cron: '*/5 * * * *' # Every 5 minutes
    - cron: '0 0 * * 0' # At 00:00 on Sunday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-package: jdk
          java-version: 11.0.9

      - name: Set Java_HOME to JDK 11
        run: |
          export JAVA_HOME=/usr/bin/java
          echo $JAVA_HOME
          java --version

      - name: Set environment variable for time (ex. 01-11-2021--05:09:52PM)
        run: |
          export TIME=$(date +"%m-%d-%Y--%r" | tr -d "[:space:]" | sed 's/:/./g')
          echo $TIME

      - name: Download and install Allure executable
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure_2.13.8-1_all.deb
          sudo dpkg -i allure_2.13.8-1_all.deb

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # mvn clean has been modified in the pom.xml file to backup allure-results history files
      # mvn test has been modified in the pom.xml file to generate allure reports from allure-results history + current test results.
      # mvn package has been modified in the pom.xml file to generate javadocs in target/javadocs/apidocs
      - name: Build with Maven
        run: mvn -B clean test package --file pom.xml

      # Create required directories
      - name: Create required directories
        run: |
          mkdir output
          mkdir output/$TIME
          mkdir output/$TIME/jars
          mkdir output/$TIME/javadocs
          mkdir output/$TIME/reports
          mkdir output/$TIME/results
          echo $TIME > time.txt
          ls -al output

      # Copies the jar file in target directory matching artifactId-version.jar (ex: Project-Template-2.0.0.jar)
      - name: Copy files that need to be archived into output directory
        run: |
          cp target/$(grep -o "<artifactId>.*</artifactId>" pom.xml | head -1 | sed "s#<artifactId>###\g" | sed "s#</artifactId>###\g")-$(grep -o "<version>.*</version>" pom.xml | head -1 | sed "s#<version>###\g" | sed "s#</version>###\g").jar output/$TIME/jars
          cp -R target/javadocs/apidocs/* output/$TIME/javadocs
          cp -R docs/allure-reports/* output/$TIME/reports
          cp -R docs/allure-results/* output/$TIME/results

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: reports+jar
          path: |
            output/$TIME